### ISSUE TITLE
Train the model error

### ISSUE THREAD

**Issue by semel1** [DwightFoster/Pytorch-TecoGAN#1]
Upon running "python3 main.py --input_video_dir TrainingDataPath --max_epochs 10" it throws an error:" unrecognized arguments: --max_epochs 10"

**Comment by dwight-foster** [comment]
I just fixed the issue it should now work. Before it was max_epoch but I changed the name of the argument to max_epochs so now it should work.

**Comment by semel1** [comment]
Traceback (most recent call last):
  File "main.py", line 266, in <module>
    for e in tqdm(range(current_epoch, args.max_epoch)):
AttributeError: 'Namespace' object has no attribute 'max_epoch'

**Comment by dwight-foster** [comment]
That has been fixed too.

**Comment by semel1** [comment]
Freezed (kind of with the blinking cursor)after:
F:\Pytorch-TecoGAN-master>python main.py --input_video_dir TrainingDataPath --max_epochs 10
  0%|                                                                  | 0/10 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 270, in <module>
    for batch_idx, (inputs, targets) in enumerate(dataloader):
  File "c:\program files\python37\lib\site-packages\torch\utils\data\dataloader.py", line 355, in __iter__
    return self._get_iterator()
  File "c:\program files\python37\lib\site-packages\torch\utils\data\dataloader.py", line 301, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "c:\program files\python37\lib\site-packages\torch\utils\data\dataloader.py", line 914, in __init__
    w.start()
  File "c:\program files\python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "c:\program files\python37\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "c:\program files\python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "c:\program files\python37\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "c:\program files\python37\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle generator objects

  0%|                                                                  | 0/10 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\program files\python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "c:\program files\python37\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "c:\program files\python37\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "c:\program files\python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "c:\program files\python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "c:\program files\python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\Pytorch-TecoGAN-master\main.py", line 270, in <module>
    for batch_idx, (inputs, targets) in enumerate(dataloader):
  File "c:\program files\python37\lib\site-packages\torch\utils\data\dataloader.py", line 355, in __iter__
    return self._get_iterator()
  File "c:\program files\python37\lib\site-packages\torch\utils\data\dataloader.py", line 301, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "c:\program files\python37\lib\site-packages\torch\utils\data\dataloader.py", line 914, in __init__
    w.start()
  File "c:\program files\python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "c:\program files\python37\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "c:\program files\python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "c:\program files\python37\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "c:\program files\python37\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "c:\program files\python37\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by dwight-foster** [comment]
Does the path you provide for the data have anything in it?

**Comment by semel1** [comment]
"TrainingDataPath" consists 277 subfolders "scene_2000" to "scene 2276" filled up with 120 frames each.
Not all videos been downloaded because of error (something like: "source is not available")

**Comment by dwight-foster** [comment]
I am not sure why you are getting that error. I did just update the code because there were a few bugs that I found so if you want to download the new update and try again hopefully it will work.

**Comment by semel1** [comment]
Just download updated "train.py". Unfortunately result the same as before: "...  The "freeze_support()" line can be omitted if the program is not going to be frozen to produce an executable. ..."

**Comment by dwight-foster** [comment]
Are you running this in windows or linux?

**Comment by semel1** [comment]
Windows  10

**Comment by dwight-foster** [comment]
Ok I think the problem had to do with windows not working with num workers I just deleted it in the repository so if you want to redownload it and try it should work.

**Comment by semel1** [comment]
This time I've got : "F:\Pytorch-TecoGAN-master>python main.py --input_video_dir TrainingDataPath --max_epochs 10
Traceback (most recent call last):
  File "main.py", line 227, in <module>
    dataloader = DataLoader(dataset, batch_size=4, shuffle=True)
  File "c:\program files\python37\lib\site-packages\torch\utils\data\dataloader.py", line 266, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore
  File "c:\program files\python37\lib\site-packages\torch\utils\data\sampler.py", line 104, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0"

**Comment by dwight-foster** [comment]
So for this you need to change the --str_dir and --end_dir values to fit the data in you folder. For example if the data starts at scene 2000 ends at scene 2276 than do --str_dir 2000 --end_dir 2276

**Comment by semel1** [comment]
Changed in main.py:
From:
parser.add_argument('--str_dir', default=1000, type=int, help='The starting index of the video directory')
parser.add_argument('--end_dir', default=1400, type=int, help='The ending index of the video directory')
parser.add_argument('--end_dir_val', default=2050, type=int,
to:
parser.add_argument('--str_dir', default=2000, type=int, help='The starting index of the video directory')
parser.add_argument('--end_dir', default=2276, type=int, help='The ending index of the video directory')
parser.add_argument('--end_dir_val', default=2050, type=int,

RuntimeError: stack expects each tensor to be equal size, but got [1, 3, 2, 128, 128] at entry 0 and [3, 3, 2, 128, 128] at entry 2

tried: 
parser.add_argument('--end_dir_val', default=2277, type=int,

the same error

**Comment by dwight-foster** [comment]
Ok I think I just fixed that error so try redownloading the code to see if it works. If it doesn't then can you give me the line where it errors out.

**Comment by semel1** [comment]
I don't see updated files. The latest updated main.py 2 days old???

**Comment by dwight-foster** [comment]
No I am talking about the train.py file in the code folder that was updated yesterday.

**Comment by DwightFoster** [comment]
No I am talking about the train.py file in the code folder that was updated yesterday.

**Comment by semel1** [comment]
Successfully performed training after replacing trin.py.
However after running "python main.py --mode inference --input_dir_LR input/test.mp4 --inferencetype video --g_checkpoint generator.pt", got weird result.
This is source (test.mp4)
https://user-images.githubusercontent.com/53234248/123290376-13754e00-d4c6-11eb-8797-1f7b96ffd6c5.mp4
and this is result.
https://user-images.githubusercontent.com/53234248/123290786-67803280-d4c6-11eb-881f-7e5b9d17d8c4.mp4

**Comment by dwight-foster** [comment]
Hmm the problem may be with the model not the code. Is your model trained on scenes like that?
